sbatch fitnesstrial_gammas/fitnesstrial_gamma-1.0.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.9.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.8.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.7.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.6.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.5.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.4.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.3.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.2.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma-0.1.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.0.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.1.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.2.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.3.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.4.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.5.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.6.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.7.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.8.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma0.9.cmd
sbatch fitnesstrial_gammas/fitnesstrial_gamma1.0.cmd
