sbatch networkbreak_gammas/networkbreak_gamma-1.0.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.9.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.8.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.7.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.6.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.5.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.4.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.3.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.2.cmd
sbatch networkbreak_gammas/networkbreak_gamma-0.1.cmd
#sbatch networkbreak_gammas/networkbreak_gamma0.0.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.1.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.2.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.3.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.4.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.5.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.6.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.7.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.8.cmd
sbatch networkbreak_gammas/networkbreak_gamma0.9.cmd
sbatch networkbreak_gammas/networkbreak_gamma1.0.cmd